name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Go tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify go.mod
        run: go mod tidy && git diff --exit-code

      - name: Run tests (race)
        run: make test

      - name: Coverage (all packages)
        run: |
          COVERPKG=$(go list ./... | tr '\n' ',' | sed 's/,$//')
          TEST_PKGS=$(go list -f '{{if or (len .TestGoFiles) (len .XTestGoFiles)}}{{.ImportPath}}{{end}}' ./... | grep -v '^$')
          if [ -z "$TEST_PKGS" ]; then echo "no test packages"; exit 0; fi

          go test $TEST_PKGS -race -covermode=atomic -coverpkg="$COVERPKG" \
            -coverprofile=coverage.out -count=1

          go tool cover -func=coverage.out | tail

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
